// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network.models;

import com.azure.core.annotation.Fluent;
import com.azure.management.network.BastionActiveSession;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The BastionActiveSessionListResult model.
 */
@Fluent
public final class BastionActiveSessionListResultInner {
    /*
     * List of active sessions on the bastion.
     */
    @JsonProperty(value = "value")
    private List<BastionActiveSession> value;

    /*
     * The URL to get the next set of results.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Get the value property: List of active sessions on the bastion.
     * 
     * @return the value value.
     */
    public List<BastionActiveSession> value() {
        return this.value;
    }

    /**
     * Set the value property: List of active sessions on the bastion.
     * 
     * @param value the value value to set.
     * @return the BastionActiveSessionListResultInner object itself.
     */
    public BastionActiveSessionListResultInner withValue(List<BastionActiveSession> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: The URL to get the next set of results.
     * 
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: The URL to get the next set of results.
     * 
     * @param nextLink the nextLink value to set.
     * @return the BastionActiveSessionListResultInner object itself.
     */
    public BastionActiveSessionListResultInner withNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }
}
