// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The FlowLogListResult model.
 */
@Fluent
public final class FlowLogListResultInner {
    /*
     * Information about flow log resource.
     */
    @JsonProperty(value = "value")
    private List<FlowLogInner> value;

    /*
     * The URL to get the next set of results.
     */
    @JsonProperty(value = "nextLink", access = JsonProperty.Access.WRITE_ONLY)
    private String nextLink;

    /**
     * Get the value property: Information about flow log resource.
     * 
     * @return the value value.
     */
    public List<FlowLogInner> value() {
        return this.value;
    }

    /**
     * Set the value property: Information about flow log resource.
     * 
     * @param value the value value to set.
     * @return the FlowLogListResultInner object itself.
     */
    public FlowLogListResultInner withValue(List<FlowLogInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: The URL to get the next set of results.
     * 
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }
}
