// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The IpGroupListResult model.
 */
@Fluent
public final class IpGroupListResultInner {
    /*
     * The list of IpGroups information resources.
     */
    @JsonProperty(value = "value")
    private List<IpGroupInner> value;

    /*
     * URL to get the next set of results.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Get the value property: The list of IpGroups information resources.
     * 
     * @return the value value.
     */
    public List<IpGroupInner> value() {
        return this.value;
    }

    /**
     * Set the value property: The list of IpGroups information resources.
     * 
     * @param value the value value to set.
     * @return the IpGroupListResultInner object itself.
     */
    public IpGroupListResultInner withValue(List<IpGroupInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: URL to get the next set of results.
     * 
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: URL to get the next set of results.
     * 
     * @param nextLink the nextLink value to set.
     * @return the IpGroupListResultInner object itself.
     */
    public IpGroupListResultInner withNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }
}
