// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The VpnServerConfigurationsResponse model.
 */
@Fluent
public final class VpnServerConfigurationsResponseInner {
    /*
     * List of VpnServerConfigurations associated with VirtualWan.
     */
    @JsonProperty(value = "vpnServerConfigurationResourceIds")
    private List<String> vpnServerConfigurationResourceIds;

    /**
     * Get the vpnServerConfigurationResourceIds property: List of
     * VpnServerConfigurations associated with VirtualWan.
     * 
     * @return the vpnServerConfigurationResourceIds value.
     */
    public List<String> vpnServerConfigurationResourceIds() {
        return this.vpnServerConfigurationResourceIds;
    }

    /**
     * Set the vpnServerConfigurationResourceIds property: List of
     * VpnServerConfigurations associated with VirtualWan.
     * 
     * @param vpnServerConfigurationResourceIds the
     * vpnServerConfigurationResourceIds value to set.
     * @return the VpnServerConfigurationsResponseInner object itself.
     */
    public VpnServerConfigurationsResponseInner withVpnServerConfigurationResourceIds(List<String> vpnServerConfigurationResourceIds) {
        this.vpnServerConfigurationResourceIds = vpnServerConfigurationResourceIds;
        return this;
    }
}
