// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AzureFirewallSku model.
 */
@Fluent
public final class AzureFirewallSku {
    /*
     * Name of an Azure Firewall SKU.
     */
    @JsonProperty(value = "name")
    private AzureFirewallSkuName name;

    /*
     * Tier of an Azure Firewall.
     */
    @JsonProperty(value = "tier")
    private String tier;

    /**
     * Creates an instance of AzureFirewallSku class.
     */
    public AzureFirewallSku() {
        tier = "Standard";
    }

    /**
     * Get the name property: Name of an Azure Firewall SKU.
     * 
     * @return the name value.
     */
    public AzureFirewallSkuName name() {
        return this.name;
    }

    /**
     * Set the name property: Name of an Azure Firewall SKU.
     * 
     * @param name the name value to set.
     * @return the AzureFirewallSku object itself.
     */
    public AzureFirewallSku withName(AzureFirewallSkuName name) {
        this.name = name;
        return this;
    }

    /**
     * Get the tier property: Tier of an Azure Firewall.
     * 
     * @return the tier value.
     */
    public String tier() {
        return this.tier;
    }

    /**
     * Set the tier property: Tier of an Azure Firewall.
     * 
     * @param tier the tier value to set.
     * @return the AzureFirewallSku object itself.
     */
    public AzureFirewallSku withTier(String tier) {
        this.tier = tier;
        return this;
    }
}
