// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network;

import com.azure.core.annotation.Fluent;
import com.azure.management.network.models.BastionShareableLinkInner;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The BastionShareableLinkListRequest model.
 */
@Fluent
public final class BastionShareableLinkListRequest {
    /*
     * List of VM references.
     */
    @JsonProperty(value = "vms")
    private List<BastionShareableLinkInner> vms;

    /**
     * Get the vms property: List of VM references.
     * 
     * @return the vms value.
     */
    public List<BastionShareableLinkInner> vms() {
        return this.vms;
    }

    /**
     * Set the vms property: List of VM references.
     * 
     * @param vms the vms value to set.
     * @return the BastionShareableLinkListRequest object itself.
     */
    public BastionShareableLinkListRequest withVms(List<BastionShareableLinkInner> vms) {
        this.vms = vms;
        return this;
    }
}
