// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ConnectionMonitorWorkspaceSettings model.
 */
@Fluent
public final class ConnectionMonitorWorkspaceSettings {
    /*
     * Log analytics workspace resource ID.
     */
    @JsonProperty(value = "workspaceResourceId")
    private String workspaceResourceId;

    /**
     * Get the workspaceResourceId property: Log analytics workspace resource
     * ID.
     * 
     * @return the workspaceResourceId value.
     */
    public String workspaceResourceId() {
        return this.workspaceResourceId;
    }

    /**
     * Set the workspaceResourceId property: Log analytics workspace resource
     * ID.
     * 
     * @param workspaceResourceId the workspaceResourceId value to set.
     * @return the ConnectionMonitorWorkspaceSettings object itself.
     */
    public ConnectionMonitorWorkspaceSettings withWorkspaceResourceId(String workspaceResourceId) {
        this.workspaceResourceId = workspaceResourceId;
        return this;
    }
}
