// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network;

import com.azure.core.annotation.Fluent;
import com.azure.core.management.SubResource;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The DdosSettings model.
 */
@Fluent
public final class DdosSettings {
    /*
     * Reference to another subresource.
     */
    @JsonProperty(value = "ddosCustomPolicy")
    private SubResource ddosCustomPolicy;

    /*
     * The DDoS protection policy customizability of the public IP. Only
     * standard coverage will have the ability to be customized.
     */
    @JsonProperty(value = "protectionCoverage")
    private DdosSettingsProtectionCoverage protectionCoverage;

    /*
     * Enables DDoS protection on the public IP.
     */
    @JsonProperty(value = "protectedIP")
    private Boolean protectedIP;

    /**
     * Get the ddosCustomPolicy property: Reference to another subresource.
     * 
     * @return the ddosCustomPolicy value.
     */
    public SubResource ddosCustomPolicy() {
        return this.ddosCustomPolicy;
    }

    /**
     * Set the ddosCustomPolicy property: Reference to another subresource.
     * 
     * @param ddosCustomPolicy the ddosCustomPolicy value to set.
     * @return the DdosSettings object itself.
     */
    public DdosSettings withDdosCustomPolicy(SubResource ddosCustomPolicy) {
        this.ddosCustomPolicy = ddosCustomPolicy;
        return this;
    }

    /**
     * Get the protectionCoverage property: The DDoS protection policy
     * customizability of the public IP. Only standard coverage will have the
     * ability to be customized.
     * 
     * @return the protectionCoverage value.
     */
    public DdosSettingsProtectionCoverage protectionCoverage() {
        return this.protectionCoverage;
    }

    /**
     * Set the protectionCoverage property: The DDoS protection policy
     * customizability of the public IP. Only standard coverage will have the
     * ability to be customized.
     * 
     * @param protectionCoverage the protectionCoverage value to set.
     * @return the DdosSettings object itself.
     */
    public DdosSettings withProtectionCoverage(DdosSettingsProtectionCoverage protectionCoverage) {
        this.protectionCoverage = protectionCoverage;
        return this;
    }

    /**
     * Get the protectedIP property: Enables DDoS protection on the public IP.
     * 
     * @return the protectedIP value.
     */
    public Boolean protectedIP() {
        return this.protectedIP;
    }

    /**
     * Set the protectedIP property: Enables DDoS protection on the public IP.
     * 
     * @param protectedIP the protectedIP value to set.
     * @return the DdosSettings object itself.
     */
    public DdosSettings withProtectedIP(Boolean protectedIP) {
        this.protectedIP = protectedIP;
        return this;
    }
}
