// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The P2SVpnConnectionRequest model.
 */
@Fluent
public final class P2SVpnConnectionRequest {
    /*
     * List of p2s vpn connection Ids.
     */
    @JsonProperty(value = "vpnConnectionIds")
    private List<String> vpnConnectionIds;

    /**
     * Get the vpnConnectionIds property: List of p2s vpn connection Ids.
     * 
     * @return the vpnConnectionIds value.
     */
    public List<String> vpnConnectionIds() {
        return this.vpnConnectionIds;
    }

    /**
     * Set the vpnConnectionIds property: List of p2s vpn connection Ids.
     * 
     * @param vpnConnectionIds the vpnConnectionIds value to set.
     * @return the P2SVpnConnectionRequest object itself.
     */
    public P2SVpnConnectionRequest withVpnConnectionIds(List<String> vpnConnectionIds) {
        this.vpnConnectionIds = vpnConnectionIds;
        return this;
    }
}
