// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The P2SVpnConnectionHealthRequest model.
 */
@Fluent
public final class P2SVpnConnectionHealthRequest {
    /*
     * The list of p2s vpn user names whose p2s vpn connection detailed health
     * to retrieve for.
     */
    @JsonProperty(value = "vpnUserNamesFilter")
    private List<String> vpnUserNamesFilter;

    /*
     * The sas-url to download the P2S Vpn connection health detail.
     */
    @JsonProperty(value = "outputBlobSasUrl")
    private String outputBlobSasUrl;

    /**
     * Get the vpnUserNamesFilter property: The list of p2s vpn user names
     * whose p2s vpn connection detailed health to retrieve for.
     * 
     * @return the vpnUserNamesFilter value.
     */
    public List<String> vpnUserNamesFilter() {
        return this.vpnUserNamesFilter;
    }

    /**
     * Set the vpnUserNamesFilter property: The list of p2s vpn user names
     * whose p2s vpn connection detailed health to retrieve for.
     * 
     * @param vpnUserNamesFilter the vpnUserNamesFilter value to set.
     * @return the P2SVpnConnectionHealthRequest object itself.
     */
    public P2SVpnConnectionHealthRequest withVpnUserNamesFilter(List<String> vpnUserNamesFilter) {
        this.vpnUserNamesFilter = vpnUserNamesFilter;
        return this;
    }

    /**
     * Get the outputBlobSasUrl property: The sas-url to download the P2S Vpn
     * connection health detail.
     * 
     * @return the outputBlobSasUrl value.
     */
    public String outputBlobSasUrl() {
        return this.outputBlobSasUrl;
    }

    /**
     * Set the outputBlobSasUrl property: The sas-url to download the P2S Vpn
     * connection health detail.
     * 
     * @param outputBlobSasUrl the outputBlobSasUrl value to set.
     * @return the P2SVpnConnectionHealthRequest object itself.
     */
    public P2SVpnConnectionHealthRequest withOutputBlobSasUrl(String outputBlobSasUrl) {
        this.outputBlobSasUrl = outputBlobSasUrl;
        return this;
    }
}
